### ISSUE TITLE
After forking the template, first CI run fails due to not finding previous tag

### ISSUE THREAD

**Issue by laszlocph** [keptn-sandbox/keptn-service-template-go#41]
Hi Keptn folks,

thank you for this awesome starting point.

When I started using it, the first PR CI run failed due to not finding a previous tag.
Here is an example: https://github.com/keptn-sandbox/onechart-service/runs/2304012646?check_suite_focus=true

I worked this around by pushing a v0.0.1 git tag to the initial commit.

Thanks

**Comment by christian-kreuzberger-dtx** [comment]
Thanks, your finding is correct.
I'll fix it.

**Comment by christian-kreuzberger-dtx** [comment]
This issue is caused by the upstream action, see https://github.com/WyriHaximus/github-action-get-previous-tag/issues/18
